lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/%env(JWT_SECRET_KEY)%'
    public_key: '%kernel.project_dir%/%env(JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(JWT_TOKENTTL)%'
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
        signature_algorithm: RS512
