nelmio_api_doc:
    documentation:
        info:
            title: FrikiRadar
            description: Aplicación de citas para frikis
            version: 1.0.0
        routes: # to filter documented routes
            path_patterns:
                - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
