image: jonaskello/docker-and-compose

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

stages:
  - build
  - deploy

cache:
  key: da-master-key
  paths:
    - vendor/

build:
  stage: build
  retry: 1
  script:
    - sed -i -e s/post-install-cmd/post-install/ -e s/post-update-cmd/post-update/ composer.json
    - mv .env.prod .env
    - docker-compose exec --user www-data -T alpine composer install --no-interaction --ignore-platform-reqs --no-suggest --no-progress --prefer-dist --optimize-autoloader
  artifacts:
    paths:
      - bin/
      - config/
      - public/
      - src/
      - templates/
      - tests/
      - translations/
      - var/
      - vendor/
      - ./*.*

deploy-prod:
  stage: deploy
  retry: 1
  dependencies:
    - build
  tags:
    - deploy-backend
  script:
    - cp -af ./ /root/frikiradar/symfony/
    - cd /root/frikiradar
    - docker-compose up -d --force-recreate
    - docker-compose exec --user www-data -T alpine php bin/console doctrine:schema:update --dump-sql --force
    - docker-compose exec --user www-data -T alpine php bin/console doctrine:cache:clear-metadata
  only:
    - master
  environment:
    name: pro
    url: https://app.frikiradar.com
