image: fabianmartin/php-symfony

stages:
  - build
  - test
  - deploy

cache:
  key: da-master-key
  paths:
    - vendor/

build:
  stage: build
  retry: 1
  script:
    - sed -i -e s/post-install-cmd/post-install/ -e s/post-update-cmd/post-update/ composer.json
    #- mv app/config/parameters.yml.env app/config/parameters.yml
    - composer install --no-interaction --ignore-platform-reqs --no-suggest --no-progress --prefer-dist --optimize-autoloader
    #- rm -f web/app_dev.php
  #artifacts:
  #  paths:
  #    - app/
  #    - bin/
  #    - src/
  #    - tests/
  #    - translations/
  #    - var/
  #    - web/
  #    - ./*.*

# RUN chmod -R +777 var
# RUN chown -R www-data:www-data /var/www/api

.phpunit:
  stage: test
  variables:
    GIT_STRATEGY: none
  allow_failure: true # XXX
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE phpunit

deploy-prod:
  stage: deploy
  retry: 1
  dependencies:
    - build
  tags:
    - deploy-prod
  script:
    - cp -af ./ /root/backend/
    - cd /root/backend
    - export $(cat /root/env.list | xargs)
    - composer run deploy-scripts
  #    - php bin/console doctrine:cache:clear-metadata
  only:
    - master
  environment:
    name: pro
    url: https://app.frikiradar.com
