image: fabianmartin/php-symfony

stages:
  - build
  - deploy

cache:
  key: da-master-key
  paths:
    - vendor/

build:
  stage: build
  retry: 1
  script:
    - mv .env.prod .env
    - composer install --no-interaction --ignore-platform-reqs --no-suggest --no-progress --prefer-dist --optimize-autoloader

deploy-prod:
  stage: deploy
  retry: 1
  dependencies:
    - build
  tags:
    - deploy-backend
  script:
    - whoami
    - pwd
    - cp -af ./ /root/frikiradar/
    - cd /root/frikiradar
    # - docker-compose up -d --force-recreate
    - php bin/console doctrine:schema:update --dump-sql --force
    - php bin/console doctrine:cache:clear-metadata
  only:
    - master
  environment:
    name: pro
    url: https://app.frikiradar.com
