image: otezvikentiy/php7.2-fpm:0.0.12

stages:
  - build
  - deploy

cache:
  key: da-master-key
  paths:
    - vendor/

build:
  stage: build
  retry: 1
  script:
    - mv .env.prod .env
    - composer install --no-interaction --ignore-platform-reqs --no-suggest --no-progress --prefer-dist --optimize-autoloader
  artifacts:
    paths:
      - bin/
      - config/
      - public/
      - src/
      - templates/
      - tests/
      - translations/
      - var/
      - vendor/
      - ./*.*

deploy-prod:
  stage: deploy
  retry: 1
  dependencies:
    - build
  tags:
    - deploy-backend
  script:
    - cp -af ./ /root/frikiradar/symfony/
    - cd /root/frikiradar
    #- docker-compose up -d --force-recreate
    - php bin/console doctrine:schema:update --dump-sql --force
    - php bin/console doctrine:cache:clear-metadata
  only:
    - master
  environment:
    name: pro
    url: https://app.frikiradar.com
