image: fabianmartin/php-symfony

stages:
  - build
  - deploy

cache:
  key: da-master-key
  paths:
    - vendor/

build:
  stage: build
  retry: 1
  script:
    - composer install --no-interaction --optimize-autoloader
    - mv .env.prod .env
  artifacts:
    paths:
      - bin/
      - config/
      - public/
      - src/
      - templates/
      - tests/
      - translations/
      - var/
      - vendor/
      - ./*.*

.phpunit:
  stage: test
  variables:
    GIT_STRATEGY: none
  allow_failure: true # XXX
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE phpunit

deploy-prod:
  stage: deploy
  retry: 1
  dependencies:
    - build
  tags:
    - deploy-backend
  script:
    - rm -rf var/cache/*
    - rm -rf var/log/*
    - cp -af ./ /root/backend/
    - cd /root/backend
    - php bin/console doctrine:schema:update --dump-sql --force
    - php bin/console doctrine:cache:clear-metadata
  only:
    - master
  environment:
    name: pro
    url: https://app.frikiradar.com
