#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user_login:
    path: /api/login
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
