#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user_login:
    path: /api/login
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
