<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZqGsAkY\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZqGsAkY/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZqGsAkY.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZqGsAkY\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZqGsAkY\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ZqGsAkY',
    'container.build_id' => '5338d390',
    'container.build_time' => 1548873237,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZqGsAkY');
