<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2UsZrT8\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2UsZrT8/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2UsZrT8.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2UsZrT8\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container2UsZrT8\srcDevDebugProjectContainer(array(
    'container.build_hash' => '2UsZrT8',
    'container.build_id' => '603b1ffc',
    'container.build_time' => 1548283075,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2UsZrT8');
