<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container87HJUFO\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container87HJUFO/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container87HJUFO.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container87HJUFO\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container87HJUFO\srcDevDebugProjectContainer(array(
    'container.build_hash' => '87HJUFO',
    'container.build_id' => '9107d8a6',
    'container.build_time' => 1548540802,
), __DIR__.\DIRECTORY_SEPARATOR.'Container87HJUFO');
